=== seffs/Baby-Steps-XML/5/Rechnung_5.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->
<!--_-_-_-_-_-_-_-_-_-_KERNELEMENTE-_-_-_-_-_-_-_-_-_-_-_-_-->
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->

  <xs:element name="UNTERNEHMENSNAME" type="xs:string"/>
  
  <xs:element name="ANREDE" type="xs:string"/>
  <xs:element name="KUNDENNAME" type="xs:string"/>
  
  <xs:element name="ADDRESSE" type="xs:string"/>
  <xs:element name="TELEFONNUMMER1" type="xs:string"/>
  <xs:element name="TELEFONNUMMER2" type="xs:string"/>
  <xs:element name="EMAIL" type="xs:string"/>
  
  <xs:element name="PLZ_ORT">
	<xs:simpleType>
		<xs:restriction base="xs:string">
		<xs:pattern value="([A-Z]{2}-)?[0-9]{4,7} [A-Z][a-z]+([- /][A-Z]?[a-z]+)*"/>
		</xs:restriction>
	</xs:simpleType>
  </xs:element> 
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->

  <xs:element name="ANZAHL" type="xs:string"/>
  <xs:element name="POSITION" type="xs:int"/>
  <xs:element name="LDATUM" type="xs:date"/>
  <xs:element name="BESCHREIBUNG" type="xs:string"/>
  <xs:element name="EINZELPREIS" type="xs:decimal"/>
  <xs:element name="GESAMTPREIS" type="xs:decimal"/>
  <xs:element name="WAEHRUNG" type="xs:string"/>
  <xs:element name="EINHEIT" type="xs:string"/>
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->

  <xs:element name="STEUERNUMMER" type="xs:string"/>
  <xs:element name="UST-ID" type="xs:string"/>
  <xs:element name="AUSTELLUNGSDATUM" type="xs:date"/>
  <xs:element name="DOKUMENTENNUMMER" type="xs:string"/>
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->
  
  <xs:element name="NETTO" type="xs:decimal"/>
  <xs:element name="MWST-GESAMT" type="xs:decimal"/>
  <xs:element name="BRUTTO" type="xs:decimal"/>
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->

	<xs:element name="KONTO-INHABER" type="xs:string"/>
	<xs:element name="BANK" type="xs:string"/>
	<xs:element name="IBAN">
		<xs:simpleType>
				<xs:restriction base="xs:string">
	 				<xs:pattern value="[A-Z0-9]{4}"/>
				</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="BLZ">
		<xs:simpleType>
				<xs:restriction base="xs:int">
	 				<xs:pattern value="[0-9]{8}"/>
				</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="KONTO-NR">
		<xs:simpleType>
				<xs:restriction base="xs:int">
	 				 <xs:pattern value="[0-9]{8,10}"/>
				</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="BIC">
		<xs:simpleType>
				<xs:restriction base="xs:string">
	 				 <xs:maxLength value="11"/>
				</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="BITCOIN" type="xs:string"/>
	<xs:element name="BAR" type="xs:string"/>
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->
<!--_-_-_-_-_-_-_-_-_-_-_-_STRUKTUR-_-_-_-_-_-_-_-_-_-_-_-_-->
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->
 
  <xs:element name="UNTERNEHMENDATEN">
    <xs:complexType>
      <xs:sequence>
      	<xs:element ref="ANREDE" minOccurs="0"/>
        <xs:element ref="UNTERNEHMENSNAME"/>
        <xs:element ref="ADDRESSE"/>
        <xs:element ref="PLZ_ORT"/>
        <xs:element ref="TELEFONNUMMER1" minOccurs="0"/>
        <xs:element ref="TELEFONNUMMER2" minOccurs="0"/>
        <xs:element ref="EMAIL" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->

  <xs:element name="KUNDEDATEN">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ANREDE"/>
        <xs:element ref="KUNDENNAME"/>
        <xs:element ref="ADDRESSE"/>
        <xs:element ref="PLZ_ORT"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->

  <xs:element name="MENGE">
  	<xs:complexType>
      <xs:sequence>
        <xs:element ref="ANZAHL"/>  
        <xs:element ref="EINHEIT" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="ITEM">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="POSITION"/>
        <xs:element ref="LDATUM"/>
        <xs:element ref="MENGE" minOccurs="0"/>
        <xs:element ref="BESCHREIBUNG"/>
        <xs:element ref="EINZELPREIS" minOccurs="0"/>
        <xs:element ref="GESAMTPREIS"/>
        <xs:element ref="WAEHRUNG"/>
      </xs:sequence>
      <xs:attribute type="xs:int" name="mehrwertsteuer" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="LEISTUNG">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ITEM" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->
  
  <xs:element name="ENTGELT">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="NETTO"/>
        <xs:element ref="MWST-GESAMT"/>
        <xs:element ref="BRUTTO"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->

  <xs:element name="KONTO">
  	<xs:complexType>
  		<xs:sequence>
  			<xs:element ref="KONTO-INHABER" minOccurs="0"/>
  			<xs:element ref="BANK" minOccurs="0"/>
  			<xs:element ref="IBAN" minOccurs="0"/>
  			<xs:element ref="BLZ" minOccurs="0"/>
  			<xs:element ref="KONTO-NR"/>
  			<xs:element ref="BIC" minOccurs="0"/>
  		</xs:sequence>	
  	</xs:complexType>
  </xs:element>
  
  
  <xs:element name="ZAHLUNGSART">
  	<xs:complexType>
  		<xs:sequence>
  			<xs:element ref="KONTO"   minOccurs="0" maxOccurs="unbounded"/>
  			<xs:element ref="BITCOIN" minOccurs="0"/>
  			<xs:element ref="BAR" minOccurs="0"/>
  		</xs:sequence>	
  	</xs:complexType>
  </xs:element>

<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->

  <xs:element name="RECHNUNG">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="UNTERNEHMENDATEN"/>
        <xs:element ref="KUNDEDATEN"/>
        <xs:choice>
	    	<xs:element ref="STEUERNUMMER"/>
	    	<xs:element ref="UST-ID"/>
	    </xs:choice>
        <xs:element ref="AUSTELLUNGSDATUM"/>
        <xs:element ref="DOKUMENTENNUMMER"/>
        <xs:element ref="LEISTUNG"/>
        <xs:element ref="ENTGELT"/>
        <xs:element ref="ZAHLUNGSART"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
<!--_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-->

  <xs:element name="RECHNUNGEN">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="RECHNUNG" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== seffs/Baby-Steps-XML/5/Rechnung_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<RECHNUNGEN
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="Rechnung_5.xsd">
  <RECHNUNG>
		<UNTERNEHMENDATEN>
			<UNTERNEHMENSNAME>Kleintier Meier GmbH</UNTERNEHMENSNAME>
			<ADDRESSE>Meierring 3</ADDRESSE>
			<PLZ_ORT>81828 Machthausen</PLZ_ORT>
			<TELEFONNUMMER1>0777/987987</TELEFONNUMMER1>
			<TELEFONNUMMER2>0777/987789</TELEFONNUMMER2>
			<EMAIL>klein.meier@tiere.de</EMAIL>
		</UNTERNEHMENDATEN>
		<KUNDEDATEN>
			<ANREDE>Frau</ANREDE>
			<KUNDENNAME>Sybille Sonder-Suttelrau</KUNDENNAME>
			<ADDRESSE>Am Süttelbach 17</ADDRESSE>
			<PLZ_ORT>77070 Siedelsuderstadt</PLZ_ORT>
		</KUNDEDATEN> 
		<UST-ID>DE333666999</UST-ID>
		<AUSTELLUNGSDATUM>2017-01-15</AUSTELLUNGSDATUM>
		<DOKUMENTENNUMMER>657321</DOKUMENTENNUMMER>
		<LEISTUNG>
			<ITEM mehrwertsteuer="19">
				<POSITION>1</POSITION>
				<LDATUM>2017-01-01</LDATUM>
				<MENGE>
					<ANZAHL>100</ANZAHL>
				</MENGE>
				<BESCHREIBUNG>Antike Holzwürmer</BESCHREIBUNG>
				<EINZELPREIS>1.50</EINZELPREIS>
				<GESAMTPREIS>150</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>2</POSITION>
				<LDATUM>2017-01-01</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
					<EINHEIT></EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Holzwurmfutter</BESCHREIBUNG>
				<EINZELPREIS>34.45</EINZELPREIS>
				<GESAMTPREIS>34.45</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>3</POSITION>
				<LDATUM>2017-01-12</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
				</MENGE>
				<BESCHREIBUNG>Steinlaus, Petrophaga lorioti</BESCHREIBUNG>
				<EINZELPREIS>777.77</EINZELPREIS>
				<GESAMTPREIS>777.77</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
		</LEISTUNG>
		<ENTGELT>
			<NETTO>808.59</NETTO>
			<MWST-GESAMT>153.63</MWST-GESAMT>
			<BRUTTO>962.22</BRUTTO>
		</ENTGELT>
		<ZAHLUNGSART>
			<KONTO>
				<KONTO-INHABER>Kleintier Meier</KONTO-INHABER>
				<BANK>Sparkasse Karlsruhe</BANK>
				<BLZ>66050101</BLZ>
				<KONTO-NR>987654321</KONTO-NR>
			</KONTO>
		</ZAHLUNGSART>
	</RECHNUNG>
	<RECHNUNG>
		<UNTERNEHMENDATEN>
			<UNTERNEHMENSNAME>Rochade-La Hoff Pharma GmbH</UNTERNEHMENSNAME>
			<ADDRESSE>An der Chemie 17</ADDRESSE>
			<PLZ_ORT>79639 Grenzych-Wahlen</PLZ_ORT>
			<TELEFONNUMMER1>07624 / 666 333 999</TELEFONNUMMER1>
			<TELEFONNUMMER2>07624 / 666 333 990</TELEFONNUMMER2>
		</UNTERNEHMENDATEN>
		<KUNDEDATEN>
			<ANREDE>Dr. med.</ANREDE>
			<KUNDENNAME>Cyprian Zottel</KUNDENNAME>
			<ADDRESSE>Soddelstrudel 5a</ADDRESSE>
			<PLZ_ORT>13023 Zotenheim</PLZ_ORT>
		</KUNDEDATEN> 
		<UST-ID>DE333666999</UST-ID>
		<AUSTELLUNGSDATUM>2017-08-08</AUSTELLUNGSDATUM>
		<DOKUMENTENNUMMER>98-798-7987</DOKUMENTENNUMMER>
		<LEISTUNG>
			<ITEM mehrwertsteuer="19">
				<POSITION>1</POSITION>
				<LDATUM>2017-08-08</LDATUM>
				<MENGE>
					<ANZAHL>3</ANZAHL>
					<EINHEIT>Packungen</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Grippenmittel "Tumifla"</BESCHREIBUNG>
				<EINZELPREIS>120</EINZELPREIS>
				<GESAMTPREIS>360</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>2</POSITION>
				<LDATUM>2017-08-08</LDATUM>
				<MENGE>
					<ANZAHL></ANZAHL>
					<EINHEIT></EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Beratung pauschal</BESCHREIBUNG>
				<GESAMTPREIS>50</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>3</POSITION>
				<LDATUM>2017-08-08</LDATUM>
				<MENGE>
					<ANZAHL>2</ANZAHL>
					<EINHEIT>Liter</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Abführmittel "Wech damit" pro Liter</BESCHREIBUNG>
				<EINZELPREIS>99.99</EINZELPREIS>
				<GESAMTPREIS>199.98</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="7">
				<POSITION>4</POSITION>
				<LDATUM>2017-08-08</LDATUM>
				<MENGE>
					<ANZAHL>2</ANZAHL>
					<EINHEIT>Stück</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Energieriegel "Satto"</BESCHREIBUNG>
				<EINZELPREIS>5.98</EINZELPREIS>
				<GESAMTPREIS>11.96</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
		</LEISTUNG>
		<ENTGELT>
			<NETTO>490.22</NETTO>
			<MWST-GESAMT>116.74</MWST-GESAMT>
			<BRUTTO>621.94</BRUTTO>
		</ENTGELT>
		<ZAHLUNGSART>
			<KONTO>
				<BANK>Deutsche Bank Lörrach</BANK>
				<IBAN>DE18</IBAN>
				<BLZ>68370034</BLZ>
				<KONTO-NR>0999666333</KONTO-NR>
				<BIC>DEUTDE6F683</BIC>
			</KONTO>
		</ZAHLUNGSART>
	</RECHNUNG>
	<RECHNUNG>
		<UNTERNEHMENDATEN>
			<UNTERNEHMENSNAME>Bestattungen Unterberg</UNTERNEHMENSNAME>
			<ADDRESSE>Oberbergweg 5</ADDRESSE>
			<PLZ_ORT>43210 Ultursingen</PLZ_ORT>
			<TELEFONNUMMER1>0478 / 777 555</TELEFONNUMMER1>
			<EMAIL>unter@berg.de</EMAIL>
		</UNTERNEHMENDATEN>
		<KUNDEDATEN>
			<ANREDE>Familie</ANREDE>
			<KUNDENNAME>Urnel</KUNDENNAME>
			<ADDRESSE>Ulturenstrasse 764</ADDRESSE>
			<PLZ_ORT>43210 Ultursingen</PLZ_ORT>
		</KUNDEDATEN> 
		<UST-ID>DE987654321</UST-ID>
		<AUSTELLUNGSDATUM>2017-10-19</AUSTELLUNGSDATUM>
		<DOKUMENTENNUMMER>893 213 11</DOKUMENTENNUMMER>
		<LEISTUNG>
			<ITEM mehrwertsteuer="19">
				<POSITION>1</POSITION>
				<LDATUM>2017-10-19</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
					<EINHEIT>Stk.</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Urne,eiche massiv"</BESCHREIBUNG>
				<GESAMTPREIS>360.00</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>2</POSITION>
				<LDATUM>2017-10-19</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
					<EINHEIT>Stk.</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Überführung Krematorium Feuerbach inkl. Begleitpersonal</BESCHREIBUNG>
				<GESAMTPREIS>349.00</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>3</POSITION>
				<LDATUM>2017-10-19</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
					<EINHEIT>Stk.</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Dekoration</BESCHREIBUNG>
				<GESAMTPREIS>149.50</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>4</POSITION>
				<LDATUM>2017-10-19</LDATUM>
				<MENGE>
					<ANZAHL>40</ANZAHL>
					<EINHEIT>Stk.</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Trauerkarten inkl. Briefmarken</BESCHREIBUNG>
				<EINZELPREIS>2.00</EINZELPREIS>
				<GESAMTPREIS>80.00</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
		</LEISTUNG>
		<ENTGELT>
			<NETTO>738.23</NETTO>
			<MWST-GESAMT>140.26</MWST-GESAMT>
			<BRUTTO>878.49</BRUTTO>
		</ENTGELT>
		<ZAHLUNGSART>
			<KONTO>
				<IBAN>DE16</IBAN>
				<BLZ>66050101</BLZ>
				<KONTO-NR>0077889911</KONTO-NR>
			</KONTO>
			<KONTO>
				<BANK>UBS Zuerich</BANK>
				<BLZ>66050101</BLZ>
				<KONTO-NR>75847683</KONTO-NR>
				<BIC>UBSWCHZH80H</BIC>
			</KONTO>
			<BITCOIN>
			1P82rBiJHDFSav2QrKx1bvdDRVh5QnGkkZ
			</BITCOIN>
		</ZAHLUNGSART>
	</RECHNUNG>
	<RECHNUNG>
		<UNTERNEHMENDATEN>
			<UNTERNEHMENSNAME>Weinhandel von Langres</UNTERNEHMENSNAME>
			<ADDRESSE>Emilianigasse 19</ADDRESSE>
			<PLZ_ORT>86866 Mickhausen</PLZ_ORT>
		</UNTERNEHMENDATEN>
		<KUNDEDATEN>
			<ANREDE>Seine Exzellenz der Hochwürdigste Herr Erzbischof</ANREDE>
			<KUNDENNAME>Waldus Mikksa</KUNDENNAME>
			<ADDRESSE>Fronhof 4</ADDRESSE>
			<PLZ_ORT>86152 Augsburg</PLZ_ORT>
		</KUNDEDATEN> 
		<UST-ID>DE123456789</UST-ID>
		<AUSTELLUNGSDATUM>2009-11-07</AUSTELLUNGSDATUM>
		<DOKUMENTENNUMMER>611-555-32</DOKUMENTENNUMMER>
		<LEISTUNG>
			<ITEM mehrwertsteuer="19">
				<POSITION>1</POSITION>
				<LDATUM>2009-11-07</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
					<EINHEIT>Fass</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>"Liebliche Gottesmilbe"</BESCHREIBUNG>
				<GESAMTPREIS>2299.98</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>2</POSITION>
				<LDATUM>2009-11-07</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
					<EINHEIT>Stück</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Standardweingläser "Schluck"</BESCHREIBUNG>
				<GESAMTPREIS>59.90</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
		</LEISTUNG>
		<ENTGELT>
			<NETTO>1983.09</NETTO>
			<MWST-GESAMT>376.79</MWST-GESAMT>
			<BRUTTO>2359.88</BRUTTO>
		</ENTGELT>
		<ZAHLUNGSART>
			<KONTO>
				<BANK>Pax-Bank Köln</BANK>
				<BLZ>37060193</BLZ>
				<KONTO-NR>0999666333</KONTO-NR>
			</KONTO>
		</ZAHLUNGSART>
	</RECHNUNG>
	<RECHNUNG>
		<UNTERNEHMENDATEN>
			<UNTERNEHMENSNAME>Peer Weidmann</UNTERNEHMENSNAME>
			<ADDRESSE>Kürschnergasse 77</ADDRESSE>
			<PLZ_ORT>76131 Karlsgrube</PLZ_ORT>
		</UNTERNEHMENDATEN>
		<KUNDEDATEN>
			<ANREDE>Herr</ANREDE>
			<KUNDENNAME>Claudius Artemis</KUNDENNAME>
			<ADDRESSE>Am Wolfsweiher 7</ADDRESSE>
			<PLZ_ORT>56741 Hirschhausen</PLZ_ORT>
		</KUNDEDATEN> 
		<UST-ID>Wegen Privatverkauf kein Ausweis der Umsatzsteuer nötig.</UST-ID>
		<AUSTELLUNGSDATUM>2017-08-09</AUSTELLUNGSDATUM>
		<DOKUMENTENNUMMER>1</DOKUMENTENNUMMER>
		<LEISTUNG>
			<ITEM mehrwertsteuer="19">
				<POSITION>1</POSITION>
				<LDATUM>2017-08-09</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
				</MENGE>
				<BESCHREIBUNG>Vogelschnepper, um 1600</BESCHREIBUNG>
				<GESAMTPREIS>3499.00</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>2</POSITION>
				<LDATUM>2017-08-09</LDATUM>
				<MENGE>
					<ANZAHL>200</ANZAHL>
				</MENGE>
				<BESCHREIBUNG>Schusser, um 1720</BESCHREIBUNG>
				<GESAMTPREIS>99.99</GESAMTPREIS>
				<WAEHRUNG>€</WAEHRUNG>
			</ITEM>
		</LEISTUNG>
		<ENTGELT>
			<NETTO>3024.36</NETTO>
			<MWST-GESAMT>574.63</MWST-GESAMT>
			<BRUTTO>3598.99</BRUTTO>
		</ENTGELT>
		<ZAHLUNGSART>
			<BAR>Bei Abholung</BAR>
		</ZAHLUNGSART>
	</RECHNUNG>
</RECHNUNGEN>
