=== seffs/Baby-Steps-XML/2/Rechnung_2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- "STEUER-ID" wird mit "STEUERNUMMER" ersetzt-->
<!-- ADDRESSE / PLZ_ORT in K und U Varianten umgewandelt, so dass Deklarationen eindeutig bleiben -->
<!ELEMENT RECHNUNGEN (RECHNUNG)+>
<!ELEMENT RECHNUNG (UNTERNEHMENDANTEN, KUNDEDATEN, (STEUERNUMMER | UST-ID), AUSTELLUNGSDATUM, DOKUMENTENNUMMER, LEISTUNG, ENTGELT)>
<!ELEMENT UNTERNEHMENDANTEN (ANREDE?, UNTERNEHMENSNAME, UADDRESSE, UPLZ_ORT, TELEFONNUMMER1, TELEFONNUMMER2?, EMAIL?)>
<!ELEMENT KUNDEDATEN (ANREDE, KUNDENNAME, KADDRESSE, KPLZ_ORT)>
<!ELEMENT LEISTUNG (ITEM)+>
<!ELEMENT ITEM (POSITION, LDATUM, MENGE?, BESCHREIBUNG, EINZELPREIS, GESAMTPREIS, WÄHRUNG)>
<!ELEMENT MENGE (ANZAHL, EINHEIT?)>
<!ELEMENT ENTGELT (NETTO, MWST-GESAMT, BRUTTO)>

<!ELEMENT UNTERNEHMENSNAME (#PCDATA)>
<!ELEMENT UADDRESSE (#PCDATA)>
<!ELEMENT UPLZ_ORT (#PCDATA)>
<!ELEMENT TELEFONNUMMER1 (#PCDATA)>
<!ELEMENT TELEFONNUMMER2 (#PCDATA)>
<!ELEMENT EMAIL (#PCDATA)>

<!ELEMENT ANREDE (#PCDATA)>
<!ELEMENT KUNDENNAME (#PCDATA)>
<!ELEMENT KADDRESSE (#PCDATA)>
<!ELEMENT KPLZ_ORT (#PCDATA)>

<!ELEMENT STEUERNUMMER (#PCDATA)>
<!ELEMENT UST-ID (#PCDATA)>

<!ELEMENT AUSTELLUNGSDATUM (#PCDATA)>

<!ELEMENT DOKUMENTENNUMMER (#PCDATA)>

<!ATTLIST ITEM mehrwertsteuer CDATA #REQUIRED>
<!ELEMENT POSITION (#PCDATA)>
<!ELEMENT LDATUM (#PCDATA)>
<!ELEMENT ANZAHL (#PCDATA)>
<!ELEMENT EINHEIT (#PCDATA)>
<!ELEMENT BESCHREIBUNG (#PCDATA)>
<!ELEMENT EINZELPREIS (#PCDATA)>
<!ELEMENT GESAMTPREIS (#PCDATA)>
<!ELEMENT WÄHRUNG (#PCDATA)>

<!ELEMENT NETTO (#PCDATA)>
<!ELEMENT MWST-GESAMT (#PCDATA)>
<!ELEMENT BRUTTO (#PCDATA)>

=== seffs/Baby-Steps-XML/2/Rechnung_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RECHNUNGEN SYSTEM "Rechnung_2.dtd" >
<RECHNUNGEN>
	<RECHNUNG>
		<UNTERNEHMENDANTEN>
			<UNTERNEHMENSNAME>Kleintier Meier GmbH</UNTERNEHMENSNAME>
			<UADDRESSE>Meierring 3</UADDRESSE>
			<UPLZ_ORT>81828 Machthausen</UPLZ_ORT>
			<TELEFONNUMMER1>0777/987987</TELEFONNUMMER1>
			<TELEFONNUMMER2>0777/987789</TELEFONNUMMER2>
			<EMAIL>klein.meier@tiere.de</EMAIL>
		</UNTERNEHMENDANTEN>
		<KUNDEDATEN>
			<ANREDE>Frau</ANREDE>
			<KUNDENNAME>Sybille Sonder-Suttelrau</KUNDENNAME>
			<KADDRESSE>Am Süttelbach 17</KADDRESSE>
			<KPLZ_ORT>77070 Siedelsuderstadt</KPLZ_ORT>
		</KUNDEDATEN> 
		<UST-ID>DE333666999</UST-ID>
		<AUSTELLUNGSDATUM>15.1.2017</AUSTELLUNGSDATUM>
		<DOKUMENTENNUMMER>657321</DOKUMENTENNUMMER>
		<LEISTUNG>
			<ITEM mehrwertsteuer="19">
				<POSITION>1</POSITION>
				<LDATUM>1.1.2017</LDATUM>
				<MENGE>
					<ANZAHL>100</ANZAHL>
				</MENGE>
				<BESCHREIBUNG>Antike Holzwürmer</BESCHREIBUNG>
				<EINZELPREIS>1,50</EINZELPREIS>
				<GESAMTPREIS>150</GESAMTPREIS>
				<WÄHRUNG>€</WÄHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>2</POSITION>
				<LDATUM>12.1.2017</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
					<EINHEIT></EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Holzwurmfutter</BESCHREIBUNG>
				<EINZELPREIS>34,45</EINZELPREIS>
				<GESAMTPREIS>34,45</GESAMTPREIS>
				<WÄHRUNG>€</WÄHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>3</POSITION>
				<LDATUM>12.1.2017</LDATUM>
				<MENGE>
					<ANZAHL>1</ANZAHL>
				</MENGE>
				<BESCHREIBUNG>Steinlaus, Petrophaga lorioti</BESCHREIBUNG>
				<EINZELPREIS>777,77</EINZELPREIS>
				<GESAMTPREIS>777,77</GESAMTPREIS>
				<WÄHRUNG>€</WÄHRUNG>
			</ITEM>
		</LEISTUNG>
		<ENTGELT>
			<NETTO>808,59</NETTO>
			<MWST-GESAMT>153,63</MWST-GESAMT>
			<BRUTTO>962,22</BRUTTO>
		</ENTGELT>
	</RECHNUNG>
	<RECHNUNG>
		<UNTERNEHMENDANTEN>
			<UNTERNEHMENSNAME>Rochade-La Hoff Pharma GmbH</UNTERNEHMENSNAME>
			<UADDRESSE>An der Chemie 17</UADDRESSE>
			<UPLZ_ORT>79639 Grenzych-Wahlen</UPLZ_ORT>
			<TELEFONNUMMER1>07624 / 666 333 999</TELEFONNUMMER1>
			<TELEFONNUMMER2>07624 / 666 333 990</TELEFONNUMMER2>
		</UNTERNEHMENDANTEN>
		<KUNDEDATEN>
			<ANREDE>Dr. med.</ANREDE>
			<KUNDENNAME>Cyprian Zottel</KUNDENNAME>
			<KADDRESSE>Soddelstrudel 5a</KADDRESSE>
			<KPLZ_ORT>13023 Zotenheim</KPLZ_ORT>
		</KUNDEDATEN> 
		<UST-ID>DE333666999</UST-ID>
		<AUSTELLUNGSDATUM>8.8.2017</AUSTELLUNGSDATUM>
		<DOKUMENTENNUMMER>98-798-7987</DOKUMENTENNUMMER>
		<LEISTUNG>
			<ITEM mehrwertsteuer="19">
				<POSITION>1</POSITION>
				<LDATUM>8.8.2017</LDATUM>
				<MENGE>
					<ANZAHL>3</ANZAHL>
					<EINHEIT>Packungen</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Grippenmittel "Tumifla"</BESCHREIBUNG>
				<EINZELPREIS>120</EINZELPREIS>
				<GESAMTPREIS>360</GESAMTPREIS>
				<WÄHRUNG>€</WÄHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>2</POSITION>
				<LDATUM>8.8.2017</LDATUM>
				<MENGE>
					<ANZAHL></ANZAHL>
					<EINHEIT></EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Beratung pauschal</BESCHREIBUNG>
				<EINZELPREIS></EINZELPREIS>
				<GESAMTPREIS>50</GESAMTPREIS>
				<WÄHRUNG>€</WÄHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="19">
				<POSITION>3</POSITION>
				<LDATUM>8.8.2017</LDATUM>
				<MENGE>
					<ANZAHL>2</ANZAHL>
					<EINHEIT>Liter</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Abführmittel "Wech damit" pro Liter</BESCHREIBUNG>
				<EINZELPREIS>99,99</EINZELPREIS>
				<GESAMTPREIS>199,98</GESAMTPREIS>
				<WÄHRUNG>€</WÄHRUNG>
			</ITEM>
			<ITEM mehrwertsteuer="7">
				<POSITION>4</POSITION>
				<LDATUM>8.8.2017</LDATUM>
				<MENGE>
					<ANZAHL>2</ANZAHL>
					<EINHEIT>Stück</EINHEIT>
				</MENGE>
				<BESCHREIBUNG>Energieriegel "Satto"</BESCHREIBUNG>
				<EINZELPREIS>5,98</EINZELPREIS>
				<GESAMTPREIS>11,96</GESAMTPREIS>
				<WÄHRUNG>€</WÄHRUNG>
			</ITEM>
		</LEISTUNG>
		<ENTGELT>
			<NETTO>490,22</NETTO>
			<MWST-GESAMT>116,74</MWST-GESAMT>
			<BRUTTO>621,94</BRUTTO>
		</ENTGELT>
	</RECHNUNG>
</RECHNUNGEN>
